spring:
  application:
    name: api-gateway
  mvc:
    log-resolved-exception: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
application:
  security:
    jwt:
      secret-key: 5A7234753778214125442A472D4B6150645367566B58703273357638792F423F