spring:
  application:
    name: authorization-server
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    log-resolved-exception: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka
application:
  security:
    jwt:
      secret-key: 5A7234753778214125442A472D4B6150645367566B58703273357638792F423F
      expiration: 86400000
      refresh-token:
        expiration: 604800000